# Generated by Django 4.0.4 on 2022-06-23 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_profile_image'),
        ('files', '0002_alter_file_owner_alter_shared_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shared',
            name='shared_with',
        ),
        migrations.AddField(
            model_name='shared',
            name='files',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='files.file'),
        ),
        migrations.AddField(
            model_name='shared',
            name='share_with',
            field=models.ManyToManyField(to='users.profile'),
        ),
    ]
