# Generated by Django 4.0.4 on 2022-06-28 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_remove_shared_shared_with_shared_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shared',
            name='owner',
        ),
    ]
